""" Add mailing list subscriptions

Revision ID: 33845d31103
Revises: 14fcadbc575
Create Date: 2015-02-22 15:59:59.796907

"""

# revision identifiers, used by Alembic.
revision = '33845d31103'
down_revision = '14fcadbc575'

from alembic import op
import sqlalchemy as sa

def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.create_table('mailinglist_sub',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('date', sa.DateTime(), nullable=True),
		sa.Column('email', sa.String(), nullable=True),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('email'),
		sqlite_autoincrement=True
	)
	op.create_index('post_created_idx', 'post', ['type', 'created', 'id'], unique=False)
	op.drop_index('post_type_idx', table_name='post')

def downgrade():
	op.create_index('post_type_idx', 'post', ['type', 'created', 'id'], unique=False)
	op.drop_index('post_created_idx', table_name='post')
	op.drop_table('mailinglist_sub')
